
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

http:
  server_host: 0.0.0.0
  
input_boolean:
  living_room_light:
    name: "Living Room Light"
    initial: off
  kitchen_light:
    name: "Kitchen Light"
    initial: off
  bedroom_light:
    name: "Bedroom Light"
    initial: off

input_number:
  dummy_light_brightness:
    name: Dummy Light Brightness
    min: 0
    max: 255
    step: 1
    unit_of_measurement: "lx"
    mode: slider

light:
  - platform: template
    lights:
      dummy_analog_light:
        friendly_name: "Dummy Analog Light"
        level_template: "{{ states('input_number.dummy_light_brightness') | int }}"
        turn_on:
          service: input_number.set_value
          target:
            entity_id: input_number.dummy_light_brightness
          data:
            value: 255  # Set to full brightness when turning on
        turn_off:
          service: input_number.set_value
          target:
            entity_id: input_number.dummy_light_brightness
          data:
            value: 0  # Set to off (brightness 0) when turning off
      living_room_light:
        friendly_name: "Living Room Light"
        value_template: "{{ is_state('input_boolean.living_room_light', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.living_room_light
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.living_room_light
      kitchen_light:
        friendly_name: "Kitchen Light"
        value_template: "{{ is_state('input_boolean.kitchen_light', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.kitchen_light
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.kitchen_light
      bedroom_light:
        friendly_name: "Bedroom Light"
        value_template: "{{ is_state('input_boolean.bedroom_light', 'on') }}"
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.bedroom_light
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.bedroom_light

# ----------------------------
# Simulating Temperature Sensors with Random Values
# ----------------------------
sensor:
  - platform: template
    sensors:
      living_room_temperature:
        friendly_name: "Living Room Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ 21 + (4 * (now().second / 60 - 0.5)) }}"  # Random temp based on seconds of the current time
      kitchen_temperature:
        friendly_name: "Kitchen Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ 22 + (3 * (now().second / 60 - 0.5)) }}"  # Random temp based on seconds of the current time
      bedroom_temperature:
        friendly_name: "Bedroom Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ 20 + (2 * (now().second / 60 - 0.5)) }}"  # Random temp based on seconds of the current time
      bathroom_temperature:
        friendly_name: "Bathroom Temperature"
        unit_of_measurement: "째C"
        value_template: "{{ 23 + (3 * (now().second / 60 - 0.5)) }}"  # Random temp based on seconds of the current time
      living_room_humidity:
        friendly_name: "Living Room Humidity"
        unit_of_measurement: "%"
        value_template: "{{ 45 + (10 * (now().second / 60 - 0.5)) }}"  # Random humidity based on seconds of the current time
      kitchen_humidity:
        friendly_name: "Kitchen Humidity"
        unit_of_measurement: "%"
        value_template: "{{ 50 + (15 * (now().second / 60 - 0.5)) }}"  # Random humidity based on seconds of the current time

# ----------------------------
# Simulating a Smart TV
# ----------------------------
media_player:
  - platform: template
    media_players:
      living_room_tv:
        friendly_name: "Living Room Smart TV"
        state_template: >
          {% if is_state('input_boolean.living_room_tv', 'on') %}
            playing
          {% else %}
            off
          {% endif %}
        turn_on:
          service: input_boolean.turn_on
          target:
            entity_id: input_boolean.living_room_tv
        turn_off:
          service: input_boolean.turn_off
          target:
            entity_id: input_boolean.living_room_tv
        media_content_type: "movie"
        media_title: "Fake TV Show"
        media_duration: 3600  # 1 hour long TV show
